# Generated by Django 3.1.7 on 2021-03-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='iconUrl',
            field=models.CharField(default='https://d25dk4h1q4vl9b.cloudfront.net/bundles/front/media/images/favicons/favicon-512.png', max_length=120),
            preserve_default=False,
        ),
    ]
